# -*- coding: utf-8 -*-
"""Bilingual_English_Urdu_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z9ixrnMFB9MtEFCDSRSzSTiPgqZUHSVA
"""

# Install required packages
!pip install transformers librosa audiomentations -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import random
from collections import Counter, defaultdict

import librosa
import librosa.display
from IPython.display import Audio, display

import torch
import torchaudio
from torch.utils.data import Dataset, DataLoader
from transformers import (Wav2Vec2Processor, Trainer, TrainingArguments,
                          Wav2Vec2ForSequenceClassification)
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

import warnings
warnings.filterwarnings('ignore')

print("All imports successful")
print("GPU available:", torch.cuda.is_available())

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

ENGLISH_PATH = "/content/drive/MyDrive/project1/datasets/Emotion Speech Dataset"
URDU_PATH    = "/content/drive/MyDrive/project1/urdu_dataset"

USE_ENGLISH = True
USE_URDU    = True



COMMON_EMOTIONS = ["angry", "happy", "neutral", "sad"]


MODEL_NAME = "facebook/wav2vec2-large-xlsr-53"


MAX_AUDIO_LENGTH = 16000 * 3
EPOCHS           = 10
LEARNING_RATE    = 1e-4
TEST_SIZE        = 0.2

print(" Configuration loaded")
print(f"  English dataset : {'ON' if USE_ENGLISH else 'OFF'} → {ENGLISH_PATH}")
print(f"  Urdu dataset    : {'ON' if USE_URDU    else 'OFF'} → {URDU_PATH}")
print(f"  Emotions        : {COMMON_EMOTIONS}")
print(f"  Model           : {MODEL_NAME}")

def load_dataset_from_folder(base_path, emotions, language_tag):
    """Walk folder tree, match emotion labels, return list of (path, label, language)."""
    records = []
    if not os.path.exists(base_path):
        print(f"⚠️  Path not found: {base_path}")
        return records

    for root, dirs, files in os.walk(base_path):
        folder = os.path.basename(root).lower()
        matched = next((e for e in emotions if e in folder), None)
        if matched is None:
            continue
        for f in files:
            if f.lower().endswith('.wav'):
                records.append((os.path.join(root, f), matched, language_tag))

    print(f"  [{language_tag}] Loaded {len(records)} files from {base_path}")
    return records

all_records = []

if USE_ENGLISH:
    all_records += load_dataset_from_folder(ENGLISH_PATH, COMMON_EMOTIONS, "english")

if USE_URDU:
    all_records += load_dataset_from_folder(URDU_PATH,    COMMON_EMOTIONS, "urdu")

if not all_records:
    raise RuntimeError("❌ No audio files found! Check your paths and folder names.")

groups = defaultdict(list)
for path, emotion, lang in all_records:
    groups[(emotion, lang)].append(path)

min_size = min(len(v) for v in groups.items() if True)
# recalculate correctly
min_size = min(len(v) for v in groups.values())
print(f"\nSmallest group size = {min_size}  →  all groups balanced to this")

random.seed(42)
balanced_records = []
for (emotion, lang), paths_list in groups.items():
    selected = random.sample(paths_list, min(min_size, len(paths_list)))
    for p in selected:
        balanced_records.append((p, emotion, lang))

random.shuffle(balanced_records)

# ── Build DataFrame ──────────────────────────────────────────────────────────
df = pd.DataFrame(balanced_records, columns=["audio_paths", "labels", "language"])
print(f"\n✅ Final balanced dataset: {len(df)} samples")
print("\nEmotion distribution:")
print(df["labels"].value_counts().to_string())
print("\nLanguage distribution:")
print(df["language"].value_counts().to_string())
print("\nEmotion × Language breakdown:")
print(df.groupby(["labels","language"]).size().unstack(fill_value=0).to_string())

fig, axes = plt.subplots(1, 2, figsize=(14, 4))

# Emotion distribution
sns.countplot(data=df, x="labels", palette="Set2",
              order=sorted(df["labels"].unique()), ax=axes[0])
axes[0].set_title("Emotion Distribution (All Languages)", fontsize=13)
axes[0].set_xlabel("Emotion"); axes[0].set_ylabel("Count")

# Language breakdown per emotion
df_grouped = df.groupby(["labels", "language"]).size().reset_index(name="count")
sns.barplot(data=df_grouped, x="labels", y="count", hue="language",
            palette={"english": "#4e9af1", "urdu": "#f17c4e"},
            order=sorted(df["labels"].unique()), ax=axes[1])
axes[1].set_title("Emotion Distribution by Language", fontsize=13)
axes[1].set_xlabel("Emotion"); axes[1].set_ylabel("Count")

plt.tight_layout()
plt.show()

def waveplot(data, sr, emotion, lang=""):
    plt.figure(figsize=(11, 4))
    plt.title(f"{lang.capitalize()} — {emotion.capitalize()}", size=18)
    librosa.display.waveshow(data, sr=sr, color='steelblue')
    plt.xlabel("Time (s)"); plt.ylabel("Amplitude")
    plt.tight_layout(); plt.show()

def spectrogram(data, sr, emotion, lang=""):
    plt.figure(figsize=(12, 4))
    plt.title(f"{lang.capitalize()} — {emotion.capitalize()} — Spectrogram", size=18)
    X   = librosa.stft(data)
    Xdb = librosa.amplitude_to_db(abs(X))
    librosa.display.specshow(Xdb, sr=sr, x_axis='time', y_axis='hz')
    plt.colorbar(); plt.tight_layout(); plt.show()

for lang in df["language"].unique():
    for emotion in sorted(df["labels"].unique()):
        subset = df[(df["labels"] == emotion) & (df["language"] == lang)]
        if len(subset) == 0:
            continue
        path = subset.iloc[0]["audio_paths"]
        data, sr = librosa.load(path, sr=None)
        waveplot(data, sr, emotion, lang)
        spectrogram(data, sr, emotion, lang)
        display(Audio(data, rate=sr))

sorted_emotions = sorted(df["labels"].unique())
lable_map         = {e: i for i, e in enumerate(sorted_emotions)}
inverse_lable_map = {i: e for e, i in lable_map.items()}

print("Label mapping:", lable_map)

df["labels"] = df["labels"].map(lable_map)
NUM_LABELS   = len(lable_map)
print(f"Number of classes: {NUM_LABELS}")
df.head()

class SpeechEmotionDataset(Dataset):
    def __init__(self, df, processor, max_length=MAX_AUDIO_LENGTH):
        self.df         = df.reset_index(drop=True)
        self.processor  = processor
        self.max_length = max_length

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row       = self.df.iloc[idx]
        speech, _ = librosa.load(row["audio_paths"], sr=16000)


        if len(speech) > self.max_length:
            speech = speech[:self.max_length]
        else:
            speech = np.pad(speech, (0, self.max_length - len(speech)), 'constant')


        inputs = self.processor(
            speech,
            sampling_rate=16000,
            return_tensors='pt',
            padding=True,
            return_attention_mask=True   # required for xlsr models
        )
        return {
            'input_values':   inputs.input_values.squeeze(0),
            'attention_mask': inputs.attention_mask.squeeze(0),
            'labels':         torch.tensor(row["labels"], dtype=torch.long)
        }

train_df, test_df = train_test_split(
    df, test_size=TEST_SIZE, random_state=42, stratify=df["labels"]
)
print(f"Train: {len(train_df)} samples  |  Test: {len(test_df)} samples")
print("Train label distribution:", Counter(train_df["labels"].tolist()))
print("Test  label distribution:", Counter(test_df["labels"].tolist()))

MODEL_NAME = "facebook/wav2vec2-large-xlsr-53"

from transformers import Wav2Vec2FeatureExtractor, Wav2Vec2ForSequenceClassification

print(f"Loading: {MODEL_NAME}")

processor = Wav2Vec2FeatureExtractor.from_pretrained(MODEL_NAME)

model = Wav2Vec2ForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=NUM_LABELS,
    ignore_mismatched_sizes=True
)


for param in model.wav2vec2.feature_extractor.parameters():
    param.requires_grad = False

trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"✅ Model ready  |  Trainable params: {trainable:,}  |  Labels: {lable_map}")

train_dataset = SpeechEmotionDataset(train_df, processor)
test_dataset  = SpeechEmotionDataset(test_df,  processor)

sample = train_dataset[0]
print(f"Sample shape : {sample['input_values'].shape}")
print(f"Sample label : {sample['labels'].item()} → {inverse_lable_map[sample['labels'].item()]}")

training_args = TrainingArguments(
    output_dir              = "./bilingual_emotion_model",
    eval_strategy           = "epoch",
    save_strategy           = "epoch",
    learning_rate           = LEARNING_RATE,
    per_device_train_batch_size = BATCH_SIZE,
    per_device_eval_batch_size  = BATCH_SIZE,
    num_train_epochs        = EPOCHS,
    weight_decay            = 0.01,
    warmup_ratio            = 0.1,
    load_best_model_at_end  = True,
    metric_for_best_model   = "accuracy",
    save_total_limit        = 2,
    report_to               = [],
    fp16                    = torch.cuda.is_available(),
)
print("Training arguments set")

def compute_metrics(pred):
    labels = pred.label_ids
    preds  = np.argmax(pred.predictions, axis=1)
    acc    = accuracy_score(labels, preds)
    prec, rec, f1, _ = precision_recall_fscore_support(labels, preds, average='weighted')
    return {"accuracy": acc, "precision": prec, "recall": rec, "f1": f1}

trainer = Trainer(
    model           = model,
    args            = training_args,
    train_dataset   = train_dataset,
    eval_dataset    = test_dataset,
    compute_metrics = compute_metrics,
)

print(" Training bilingual (English + Urdu) emotion model...")
trainer.train()

trainer.save_model("./bilingual_emotion_model")
processor.save_pretrained("./bilingual_emotion_model")
print("✅ Model saved to ./bilingual_emotion_model")

results = trainer.evaluate()
print("\n📊 Final Evaluation Results:")
for k, v in results.items():
    print(f"  {k}: {v:.4f}" if isinstance(v, float) else f"  {k}: {v}")

"""## 📊 Evaluation Plots"""

from sklearn.metrics import (confusion_matrix, classification_report,
    roc_curve, auc, precision_recall_curve)
from sklearn.preprocessing import label_binarize

# ── Get predictions ──────────────────────────────────────────────────────────
pred_out      = trainer.predict(test_dataset)
preds         = np.argmax(pred_out.predictions, axis=1)
true_labels   = pred_out.label_ids
probs_softmax = (lambda p: np.exp(p) / np.exp(p).sum(axis=1, keepdims=True))(pred_out.predictions)
label_names   = [inverse_lable_map[i] for i in range(NUM_LABELS)]

# Dark theme
plt.rcParams.update({
    "figure.facecolor":"#0f0f0f","axes.facecolor":"#1a1a2e","axes.edgecolor":"#444",
    "axes.labelcolor":"#e0e0e0","xtick.color":"#aaa","ytick.color":"#aaa",
    "text.color":"#e0e0e0","grid.color":"#2a2a3e","grid.linestyle":"--",
    "grid.alpha":0.5,"font.family":"monospace",
})
ACCENT,ACCENT2,ACCENT3 = "#00d4ff","#ff6b6b","#a8ff78"


fig, ax = plt.subplots(figsize=(8,6))
cm = confusion_matrix(true_labels, preds)
sns.heatmap(cm, annot=True, fmt="d", cmap="YlOrRd",
            xticklabels=label_names, yticklabels=label_names, ax=ax)
ax.set_title("Confusion Matrix — Bilingual SER", fontsize=14, color=ACCENT, pad=15)
ax.set_xlabel("Predicted"); ax.set_ylabel("True")
plt.tight_layout(); plt.savefig("confusion_matrix.png",dpi=150); plt.show()


fig, ax = plt.subplots(figsize=(8,6))
cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True)
sns.heatmap(cm_norm, annot=True, fmt=".2f", cmap="Blues",
            xticklabels=label_names, yticklabels=label_names, ax=ax, vmin=0, vmax=1)
ax.set_title("Normalised Confusion Matrix", fontsize=14, color=ACCENT, pad=15)
ax.set_xlabel("Predicted"); ax.set_ylabel("True")
plt.tight_layout(); plt.savefig("confusion_matrix_norm.png",dpi=150); plt.show()


report = classification_report(true_labels, preds, target_names=label_names, output_dict=True)
rdf = pd.DataFrame(report).T.iloc[:-3]
fig, ax = plt.subplots(figsize=(9,5))
x = np.arange(len(rdf)); w = 0.25
ax.bar(x-w, rdf["precision"], w, label="Precision", color=ACCENT,  alpha=0.85)
ax.bar(x,   rdf["recall"],    w, label="Recall",    color=ACCENT2, alpha=0.85)
ax.bar(x+w, rdf["f1-score"],  w, label="F1-Score",  color=ACCENT3, alpha=0.85)
ax.set_xticks(x); ax.set_xticklabels(rdf.index, rotation=30, ha="right")
ax.set_ylim(0,1.1); ax.set_ylabel("Score"); ax.legend()
ax.set_title("Per-Class Metrics", fontsize=14, color=ACCENT); ax.grid(axis="y")
plt.tight_layout(); plt.savefig("per_class_metrics.png",dpi=150); plt.show()


history    = trainer.state.log_history
train_loss = [(e["epoch"],e["loss"])      for e in history if "loss"      in e and "eval_loss" not in e]
eval_loss  = [(e["epoch"],e["eval_loss"]) for e in history if "eval_loss" in e]
if train_loss:
    fig, ax = plt.subplots(figsize=(9,5))
    te,tl = zip(*train_loss); ax.plot(te,tl,color=ACCENT, lw=2,marker="o",ms=4,label="Train Loss")
    if eval_loss:
        ve,vl = zip(*eval_loss); ax.plot(ve,vl,color=ACCENT2,lw=2,marker="s",ms=4,label="Val Loss")
    ax.set_xlabel("Epoch"); ax.set_ylabel("Loss")
    ax.set_title("Training & Validation Loss", fontsize=14, color=ACCENT)
    ax.legend(); ax.grid(True); plt.tight_layout()
    plt.savefig("loss_curve.png",dpi=150); plt.show()


eval_acc = [(e["epoch"],e["eval_accuracy"]) for e in history if "eval_accuracy" in e]
eval_f1  = [(e["epoch"],e["eval_f1"])       for e in history if "eval_f1"       in e]
if eval_acc:
    fig, ax = plt.subplots(figsize=(9,5))
    ea,ac = zip(*eval_acc); ax.plot(ea,ac,color=ACCENT3,lw=2,marker="o",ms=4,label="Val Accuracy")
    if eval_f1:
        ef,f1v = zip(*eval_f1); ax.plot(ef,f1v,color=ACCENT2,lw=2,marker="s",ms=4,label="Val F1")
    ax.set_ylim(0,1.05); ax.set_xlabel("Epoch"); ax.set_ylabel("Score")
    ax.set_title("Validation Accuracy & F1 over Epochs", fontsize=14, color=ACCENT)
    ax.legend(); ax.grid(True); plt.tight_layout()
    plt.savefig("accuracy_f1_curve.png",dpi=150); plt.show()


labels_bin = label_binarize(true_labels, classes=list(range(NUM_LABELS)))
fig, ax = plt.subplots(figsize=(9,7))
colors = plt.cm.plasma(np.linspace(0.1,0.9,NUM_LABELS))
for i,color in enumerate(colors):
    if labels_bin[:,i].sum()==0: continue
    fpr,tpr,_ = roc_curve(labels_bin[:,i], probs_softmax[:,i])
    ax.plot(fpr,tpr,color=color,lw=1.8,label=f"{label_names[i]} (AUC={auc(fpr,tpr):.2f})")
ax.plot([0,1],[0,1],"k--",lw=1,alpha=0.5)
ax.set_xlabel("FPR"); ax.set_ylabel("TPR")
ax.set_title("ROC Curves (One-vs-Rest)", fontsize=14, color=ACCENT)
ax.legend(loc="lower right",fontsize=9); ax.grid(True); plt.tight_layout()
plt.savefig("roc_curves.png",dpi=150); plt.show()


fig, ax = plt.subplots(figsize=(9,7))
for i,color in enumerate(colors):
    if labels_bin[:,i].sum()==0: continue
    prec,rec,_ = precision_recall_curve(labels_bin[:,i], probs_softmax[:,i])
    ax.plot(rec,prec,color=color,lw=1.8,label=f"{label_names[i]} (AUC={auc(rec,prec):.2f})")
ax.set_xlabel("Recall"); ax.set_ylabel("Precision")
ax.set_title("Precision-Recall Curves", fontsize=14, color=ACCENT)
ax.legend(loc="upper right",fontsize=9); ax.grid(True); plt.tight_layout()
plt.savefig("pr_curves.png",dpi=150); plt.show()


max_conf = probs_softmax.max(axis=1); correct = (preds==true_labels)
fig, ax = plt.subplots(figsize=(9,5))
ax.hist(max_conf[correct], bins=20,alpha=0.75,color=ACCENT3,label="Correct")
ax.hist(max_conf[~correct],bins=20,alpha=0.75,color=ACCENT2,label="Wrong")
ax.set_xlabel("Confidence (max softmax)"); ax.set_ylabel("Count")
ax.set_title("Prediction Confidence Distribution", fontsize=14, color=ACCENT)
ax.legend(); ax.grid(True); plt.tight_layout()
plt.savefig("confidence_distribution.png",dpi=150); plt.show()


from sklearn.metrics import f1_score, matthews_corrcoef
summary = {
    "Accuracy":       accuracy_score(true_labels,preds),
    "Weighted F1":    f1_score(true_labels,preds,average="weighted"),
    "Macro F1":       f1_score(true_labels,preds,average="macro"),
    "MCC":            matthews_corrcoef(true_labels,preds),
    "Avg Confidence": max_conf.mean(),
}
fig, ax = plt.subplots(figsize=(8,3.5)); ax.axis("off")
rows = [[k,f"{v:.4f}"] for k,v in summary.items()]
tbl  = ax.table(cellText=rows, colLabels=["Metric","Value"], loc="center", cellLoc="center")
tbl.auto_set_font_size(False); tbl.set_fontsize(12); tbl.scale(1.4,2.2)
for (r,c),cell in tbl.get_celld().items():
    cell.set_edgecolor("#333")
    if r==0:
        cell.set_facecolor("#00d4ff"); cell.set_text_props(color="#0f0f0f",weight="bold")
    else:
        cell.set_facecolor("#1a1a2e" if r%2 else "#222235")
        cell.set_text_props(color="#e0e0e0")
ax.set_title("Bilingual SER — Model Performance Summary", fontsize=14, color=ACCENT, pad=10)
plt.tight_layout(); plt.savefig("summary_metrics.png",dpi=150); plt.show()
print("\n✅ All plots saved.")

"""## 🌐 Per-Language Accuracy Breakdown"""

device = 'cuda' if torch.cuda.is_available() else 'cpu'
model.to(device); model.eval()

results_by_lang = defaultdict(lambda: {"correct": 0, "total": 0})

test_df_reset = test_df.reset_index(drop=True)
for idx in range(len(test_dataset)):
    row  = test_df_reset.iloc[idx]
    lang = row["language"]
    true = int(test_dataset[idx]["labels"])

    input_values = test_dataset[idx]["input_values"].unsqueeze(0).to(device)
    with torch.no_grad():
        pred = model(input_values).logits.argmax(dim=-1).item()

    results_by_lang[lang]["total"]   += 1
    results_by_lang[lang]["correct"] += int(pred == true)

print("\n📊 Per-Language Accuracy:")
print(f"  {'Language':<12} {'Correct':>8} {'Total':>8} {'Accuracy':>10}")
print("  " + "-"*42)
for lang, counts in results_by_lang.items():
    acc = counts['correct'] / counts['total'] * 100
    print(f"  {lang:<12} {counts['correct']:>8} {counts['total']:>8} {acc:>9.1f}%")

"""## 🔍 Test Random Predictions"""

for i in range(10):
    idx        = random.randrange(0, len(test_dataset))
    true_label = inverse_lable_map[int(test_dataset[idx]["labels"])]
    lang       = test_df_reset.iloc[idx]["language"]

    input_values = test_dataset[idx]["input_values"].unsqueeze(0).to(device)
    with torch.no_grad():
        pred_class = model(input_values).logits.argmax(dim=-1).item()
    pred_label = inverse_lable_map[pred_class]

    status = "✅" if true_label == pred_label else "❌"
    print(f"Sample {i+1} [{lang:<8}]: True={true_label:<8} | Predicted={pred_label:<8} {status}")

